using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Mvc.ApiExplorer;
using Microsoft.Extensions.DependencyInjection;
using Scalar.AspNetCore;

namespace Callora.Core.Api.OpenApi;

/// <summary>
/// OpenAPI wiring for the host backend (Phase C0): two documents — platform "api"
/// and "workspace" — generated by <c>Microsoft.AspNetCore.OpenApi</c> and served
/// through the Scalar reference UI. Replaces Swashbuckle.
/// </summary>
public static class BackendOpenApiExtensions
{
    private const string PlatformDocument = "api";
    private const string WorkspaceDocument = "workspace";

    public static IServiceCollection AddBackendOpenApi(this IServiceCollection services)
    {
        services.AddOpenApi(PlatformDocument, options =>
        {
            options.ShouldInclude = description => !IsWorkspace(description);
            options.AddDocumentTransformer((document, context, cancellationToken) =>
            {
                document.Info = new() { Title = "Callora Host Backend API", Version = "v1" };
                return Task.CompletedTask;
            });
            options.AddDocumentTransformer<ApiKeySecuritySchemeTransformer>();
        });

        services.AddOpenApi(WorkspaceDocument, options =>
        {
            options.ShouldInclude = IsWorkspace;
            options.AddDocumentTransformer((document, context, cancellationToken) =>
            {
                document.Info = new() { Title = "Callora Workspace API", Version = "v1" };
                return Task.CompletedTask;
            });
            options.AddDocumentTransformer<ApiKeySecuritySchemeTransformer>();
        });

        return services;
    }

    public static WebApplication MapBackendOpenApi(this WebApplication app)
    {
        // Serves each document at /openapi/{documentName}.json.
        app.MapOpenApi();
        app.MapScalarApiReference(options =>
        {
            options.AddDocument(PlatformDocument, "Host Backend API");
            options.AddDocument(WorkspaceDocument, "Workspace API");
        });
        return app;
    }

    private static bool IsWorkspace(ApiDescription description)
    {
        var path = "/" + (description.RelativePath ?? string.Empty).TrimStart('/');
        return path.StartsWith("/workspace/", StringComparison.OrdinalIgnoreCase);
    }
}
