using Callora.Core.Application.Plugins.Contracts;
using Callora.Core.Domain.Plugins.Contracts;

namespace Callora.Plugins.SurfaceDemo;

/// <summary>
/// Example host-managed plugin generated by the Callora scaffold CLI.
/// </summary>
public sealed class SurfaceDemoPlugin : IHostManagedPlugin
{
    public string PluginId => "surface-demo";

    public string DisplayName => "Surface Demo";

    public ValueTask StartAsync(IHostPluginContext context, CancellationToken cancellationToken = default) =>
        ValueTask.CompletedTask;

    public ValueTask StopAsync(CancellationToken cancellationToken = default) =>
        ValueTask.CompletedTask;
}
