// <auto-generated />
using Callora.Plugin.Composer.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Callora.Plugin.Composer.Infrastructure.Persistence.Migrations
{
    // EF findet eine Migration nur über ihr [Migration]-Attribut — ohne diese Datei wendet
    // MigrateAsync sie nie an. Das Zielmodell kommt aus derselben Quelle wie der Snapshot.
    [DbContext(typeof(ComposerDbContext))]
    [Migration("20260807090000_InitialComposerSchema")]
    partial class InitialComposerSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder) =>
            ComposerModelDefinition.Build(modelBuilder);
    }
}
