// <auto-generated />
using Callora.Plugin.Composer.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace Callora.Plugin.Composer.Infrastructure.Persistence.Migrations
{
    // Von Hand gepflegt: das EF-Tooling kann diesen Kontext nicht bauen, weil Callora.Core nicht
    // im Plugin-Output liegt. Das Modell selbst steht in ComposerModelDefinition.
    [DbContext(typeof(ComposerDbContext))]
    partial class ComposerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder) =>
            ComposerModelDefinition.Build(modelBuilder);
    }
}
