// <auto-generated />
using System;
using Callora.Plugin.Communication.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Callora.Plugin.Communication.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CommunicationDbContext))]
    [Migration("20260805190000_RemoveDormantSipLines")]
    partial class RemoveDormantSipLines
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("plugin_communication")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Callora.Plugin.Communication.Domain.Accounts.SipAccount", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("LastRegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastStatusChangeAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxConcurrentCalls")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("WorkspaceKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceKey");

                    b.ToTable("sip_accounts", "plugin_communication");
                });

            modelBuilder.Entity("Callora.Plugin.Communication.Domain.Calls.CallLog", b =>
                {
                    b.Property<Guid>("RecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AccountId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("AnsweredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DisconnectCause")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HandledBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LocalIdentity")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RemoteParty")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkspaceKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid");

                    b.HasKey("RecordId");

                    b.HasIndex("WorkspaceKey", "StartedAt");

                    b.HasIndex("WorkspaceKey", "AccountId", "Id")
                        .IsUnique();

                    b.ToTable("call_logs", "plugin_communication");
                });

            modelBuilder.Entity("Callora.Plugin.Communication.Domain.Streaming.MediaStreamSession", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CallId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ConnectTokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ConsumerRef")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("WorkspaceKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("ConnectTokenHash")
                        .IsUnique();

                    b.HasIndex("WorkspaceKey");

                    b.ToTable("media_stream_sessions", "plugin_communication");
                });

            modelBuilder.Entity("Callora.Plugin.Communication.Domain.Accounts.SipAccount", b =>
                {
                    b.OwnsOne("Callora.Plugin.Communication.Domain.Accounts.SipConnection", "Connection", b1 =>
                        {
                            b1.Property<string>("SipAccountId")
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("Authentication")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("authentication");

                            b1.Property<string>("Host")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("host");

                            b1.Property<string>("InboundNumbers")
                                .HasColumnType("text")
                                .HasColumnName("inbound_numbers");

                            b1.Property<string>("Mode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("mode");

                            b1.Property<string>("OutboundProxy")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("outbound_proxy");

                            b1.Property<int>("Port")
                                .HasColumnType("integer")
                                .HasColumnName("port");

                            b1.Property<int?>("RegistrationExpirySeconds")
                                .HasColumnType("integer")
                                .HasColumnName("registration_expiry_seconds");

                            b1.Property<string>("Transport")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("transport");

                            b1.HasKey("SipAccountId");

                            b1.ToTable("sip_accounts", "plugin_communication");

                            b1.WithOwner()
                                .HasForeignKey("SipAccountId");
                        });

                    b.Navigation("Connection")
                        .IsRequired();
                });

            modelBuilder.Entity("Callora.Plugin.Communication.Domain.Streaming.MediaStreamSession", b =>
                {
                    b.OwnsOne("Callora.Plugin.Communication.Abstractions.AudioFormat", "Format", b1 =>
                        {
                            b1.Property<string>("MediaStreamSessionId")
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("Codec")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("audio_codec");

                            b1.Property<int>("FrameMilliseconds")
                                .HasColumnType("integer")
                                .HasColumnName("audio_frame_ms");

                            b1.Property<int>("SampleRateHz")
                                .HasColumnType("integer")
                                .HasColumnName("audio_sample_rate_hz");

                            b1.HasKey("MediaStreamSessionId");

                            b1.ToTable("media_stream_sessions", "plugin_communication");

                            b1.WithOwner()
                                .HasForeignKey("MediaStreamSessionId");
                        });

                    b.Navigation("Format")
                        .IsRequired();
                });

            modelBuilder.Entity("Callora.Plugin.Communication.Domain.Calls.CallEventOutboxEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkspaceKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("DeliveredAt", "NextAttemptAt");

                    b.ToTable("call_event_outbox", "plugin_communication");
                });

#pragma warning restore 612, 618
        }
    }
}
